# Generated by Django 2.2.13 on 2020-06-16 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uinfin', models.CharField(max_length=9)),
                ('sex', models.CharField(max_length=6)),
                ('race', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True)),
                ('mobileno', models.CharField(max_length=15)),
                ('houssingtype', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
