# Generated by Django 2.2.13 on 2020-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_auto_20200617_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='houssingtype',
            new_name='housetype',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobileno',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_block',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_floor',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_unit',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
